### ISSUE TITLE
How can remove white screen?

### ISSUE THREAD

**Issue by fuadmostafij6** [ToyZ-95/another_flutter_splash_screen#7]

**Comment by ToyZ-95** [comment]
Hi, @fuadmostafij6 , which white screen you are talking about? can you please give some code or something for reference?

**Comment by duckls** [comment]
启动白屏一瞬间

**Comment by ToyZ-95** [comment]
> 启动白屏一瞬间

English please

**Comment by ToyZ-95** [comment]
Closing this issue as white screen shows before the flutter app starts.
